package org.myworkflows.domain.event;

import lombok.Builder;
import lombok.Getter;

import java.util.Map;
import java.util.UUID;

/**
 * @author Mihai Surdeanu
 * @since 1.0.0
 */
@Builder
@Getter
public class WorkflowDefinitionOnSubmitEvent implements Event {

    private final UUID token;
    private final Integer workflowTemplateId; // null for manual run or set if is generated by an WorkflowTemplate
    private final Map<String, Object> workflowParameters;
    private final Object workflowDefinitionScript; // allowed object types: WorkflowDefinitionScript or String

}
