server:
  port: 8080
  # Properties for enabling HTTPS
  #ssl:
  #  enabled: true
  #  key-store: keystore.p12
  #  key-store-password: yourpassword
  #  key-store-type: PKCS12
  #  key-alias: myalias

spring:
  jpa:
    # Prints current SQL query executed. Used for debug purposes.
    show-sql: false
    # Database type is SQLite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      # Avoid creating stuff automatically
      ddl-auto: none
    properties:
      hibernate:
        # Pretty print all SQL queries in console
        format_sql: true
  datasource:
    # Property to specify the location of the main SQLite database
    url: jdbc:sqlite:database.db
    # Database driver
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false
  threads:
    virtual:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    # Property for defining root level for application logs.
    root: INFO # use DEBUG as a value for activating DEBUG level
    # Uncomment the following property if you want to activate debug level only for classes created by this app.
    #org:
    #  myworkflows: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 100MB # Limit for log file size
      max-history: 10 # Activate log rolling
  file:
    name: application.log # Default name for a logging file

my-workflows:
  config:
    base:
      logo-src: "src/main/resources/META-INF/resources/logo.png"
      name: "My Workflows"
      url: "https://myworkflows.org"
      version: "1.1"
    encryption:
      # Algorithm used to encrypt cookies for storing sensitive data
      algorithm: "AES"
      # Secret key used to encrypt cookies internally for storing sensitive data
      secret-key: "$2a$10$2KfdoXL0u.t4WnK7h9PZjOLnJZir7yvD3i84SlPI4k3oChci0ZR2"
    library:
      base-directory: "libs"
    file-source:
      base-directory: "files"
