server:
  port: 8080

spring:
  jpa:
    # Prints current SQL query executed. Used for debug purposes.
    show-sql: false
    # Database type is SQLite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      # Avoid creating stuff automatically
      ddl-auto: none
    properties:
      hibernate:
        # Pretty print all SQL queries in console
        format_sql: true
  datasource:
    # Property to specify location of main SQLite database
    url: jdbc:sqlite:database.db
    # Database driver
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false

my-workflows:
  config:
    executor:
      # Number of threads used to schedule workflow templates using cron-jobs.
      workflow-scheduler-pool-size: 2
      # Number of threads part of workflow pool size.
      # Those threads are eligible to process submitted workflows.
      workflow-pool-size: 4
      # Capacity for workflow pool queue
      workflow-pool-capacity: 1000
      # Number of threads part of event pool size.
      # Multiple components part of this tool needs to communicate in async mode.
      event-pool-size: 2
      # Capacity for event pool queue
      event-pool-capacity: 1000
