server:
  port: 8080
  # Properties for enabling HTTPS
  #ssl:
  #  enabled: true
  #  key-store: keystore.p12
  #  key-store-password: yourpassword
  #  key-store-type: PKCS12
  #  key-alias: myalias

spring:
  jpa:
    # Prints current SQL query executed. Used for debug purposes.
    show-sql: false
    # Database type is SQLite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      # Avoid creating stuff automatically
      ddl-auto: none
    properties:
      hibernate:
        # Pretty print all SQL queries in console
        format_sql: true
  datasource:
    # Property to specify location of main SQLite database
    url: jdbc:sqlite:database.db
    # Database driver
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    # Property for defining root level for application logs.
    root: INFO # use DEBUG as value for activating DEBUG level
    # Uncomment the following property if you want to activate debug level only for classes created by this app.
    #org:
    #  myworkflows: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 100MB # Limit for log file size
      max-history: 10 # Activate log rolling
  file:
    name: application.log # Default name for logging file

my-workflows:
  config:
    executor:
      # Number of threads used to schedule workflow templates using cron-jobs.
      workflow-scheduler-pool-size: 2
      # Number of threads part of workflow pool size.
      # Those threads are eligible to process submitted workflows.
      workflow-pool-size: 4
      # Capacity for workflow pool queue
      workflow-pool-capacity: 1000
      # Number of threads part of event pool size.
      # Multiple components part of this tool needs to communicate in async mode.
      event-pool-size: 2
      # Capacity for event pool queue
      event-pool-capacity: 1000
