server:
  port: 8080

spring:
  jpa:
    # Prints current SQL query executed. Used for debug purposes.
    show-sql: true
    # Database type is SQLite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      # Avoid creating stuff automatically
      ddl-auto: none
    properties:
      hibernate:
        # Pretty print all SQL queries in console
        format_sql: true
  datasource:
    # Property to specify location of main SQLite database
    url: jdbc:sqlite:database.db
    # Database driver
    driver-class-name: org.sqlite.JDBC
  mustache:
    check-template-location: false

registry:
  users:
    -
      username: "user"
      password: "$2a$10$LEPDrW3rJp98sJ96Rb2KgOaGwDJcMdGz0BPcDTRBgM9PhY2g2KmA2"
  admins:
    -
      username: "admin"
      password: "$2a$10$omNibHqZ1p6kx4/bLMNWJ.82c30oAdg0asgGWr9jB9o2zwhim3G7O"

settings:
  test-scenario-scheduler:
    # Number of threads part of test scenario scheduling pool
    pool-size: 2
    # A thread prefix to easily identify threads from scheduling pool
    thread-name-prefix: "test-scenario-pool-"
