name: Build, Test, Release and Deploy

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: 'github'
        cache: maven
    - name: Configure Git user
      run: |
        git config user.email "release-bot@myworkflows.org"
        git config user.name "Release Bot"
    - name: Release a new version
      run: mvn -B release:prepare release:perform --file pom.xml --settings settings.xml
      env:
        GITHUB_USERNAME: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
    - name: Upload WAR file
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/myworkflows*.war
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
