name: Build, Test and Release

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: 'github'
        cache: maven

    - name: Configure Git user
      run: |
        git config user.email "release-bot@myworkflows.org"
        git config user.name "Release Bot"

    - name: Release a new version
      run: mvn -B release:prepare release:perform --file pom.xml --settings settings.xml
      env:
        GITHUB_USERNAME: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
